#!/bin/bash
python3.9 -m venv test_temp_venv
source ./test_temp_venv/bin/activate
pip install wheel
pip install ./packages/metadata_ingestion
pip install pytest
pytest
ec=$?
deactivate
rm -r -f test_temp_venv
exit $ec
