#!/bin/bash
python3.9 -m venv .temp_venv
source .temp_venv/bin/activate
pip install wheel
pip install ./packages/metadata_ingestion
pip install pytest
pytest
ec=$?
deactivate
rm -r -f .temp_venv
exit $ec
