# Configuration file template for the metadata_ingestion package. When used,
# the package looks for this configuration file in the directory given in the
# CONFIG_DIR environment variable. This file should be named
# opendal_ingestion.yaml

# Location of other configuration files
# (The ones loaded by _loadcfg.py, please see readme)
config_dir: '/home/ubuntu/configs'

# Delays for consecutive retries of the harvester (4 retries with backoff)
delays: [10, 30, 120, 600]

# Use this key to represent the internal data of an xml node under
rep_textkey: _content # this will replace #text in xml data

# Format used for date fields in the translated data
date_format: '%Y-%m-%d'

# Number of days added to date that is 'now'
# Set this depending on the interval at which you're going to update
# the database, so the 'now' data is always highger then the current date
now_add_days: 14
