# Configuration file template for the metadata_ingestion package. When used,
# the package looks for this configuration file in the directory given in the
# CONFIG_DIR environment variable. This file should be named
# opendal_ingestion.yaml

# Location of other configuration files
# (The ones loaded by _loadcfg.py, please see readme)
config_dir: '/home/ubuntu/configs'

# Delays for consecutive retries of the harvester (4 retries with backoff)
delays: [10, 30, 120, 600]

# Use this key to represent the internal data of an xml node under
rep_textkey: _content # this will replace #text in xml data

# Data Translation
date_format: '%Y-%m-%d'
now_add_days: 14 # Number of days added to date that is 'now'
